Repository choisy/sptools, pull requests merged in 2018-11, with the labels that each got.

#6 Adding the split_on_poly function
  NAMESPACE
  R/split_on_poly.R
  man/split_on_poly.Rd
Labels: new function

#7 Adding the add_from_raster function
  NAMESPACE
  R/add_from_raster.R
  man/add_from_raster.Rd
Labels: new function

#9 Adding the na_exclude function
  NAMESPACE
  R/na_exclude.R
  man/na_exclude.Rd
Labels: new function

#15 Addressing issue #14
  NAMESPACE
  R/points_in_polygon.R
  man/points_in_polygon.Rd
Labels: bug fix

#18 Fixing issue #17
  R/resample_from_grid.R
Labels: bug fix

#16 Fixing issues #13
  NAMESPACE
  R/add_from_raster.R
  man/add_from_raster.Rd
Labels: enhancement

#23 Addressing issue #29
  NAMESPACE
  R/add_variable.R
  man/add_variable_sp.Rd
  man/add_variable_spdf.Rd
Labels: new function

#24 Adding the remove_var function
  NAMESPACE
  R/remove_var.R
  man/remove_var.Rd
Labels: new function

#25 Adding function change_data
  NAMESPACE
  R/change_data.R
  man/change_data.Rd
Labels: new function

#26 Sp grid2 raster
  NAMESPACE
  R/add_variable.R
  R/cut_sppoly.R
  R/grid2raster.R
  R/largest_polygons.R
  R/points_in_polygon.R
  R/remove_data.R
  R/resample_from_grid.R
  R/utils.R
  man/add_variable_spts.Rd
  man/grid2raster.Rd
Labels: new function

#28 Adding the sfpts2df function
  NAMESPACE
  R/sfpts2df.R
  man/sfpts2df.Rd
  tests/testthat/test_sf_aggregate_lst.R
Labels: new function
